# -*- coding: utf-8 -*-
"""GenAI-ML-HW5-Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCW_bF5pnkYLy6NaQ3y7Nkvvp28KjHay

# 2025 GENAI-ML-HW5
# Regression
In this assignment, you are expected to use linear regression and multi layer perceptron (MLP) model to predict the metacritic score on the famous game platform, Steam. For more information, please check the homework slide.
HW5 Slide Link :

https://docs.google.com/presentation/d/1ysys__L1HKLPV2LX0u-KMP0LD1XamhNCY_hq29k-I0A/edit?usp=sharing

## Check GPU Status
"""


"""# Import Modules

"""

import random
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from tqdm import tqdm
import matplotlib.pyplot as plt

"""# Set Random Seed"""

# ===== 設定亂數種子，可以固定結果 =====
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# TODO - 自行選擇亂數種子
set_seed(20251024)



"""# Preview Training Data"""

# ===== 載入訓練資料集 =====
train_df = pd.read_csv("GENAI-ML-2025-HW5-Data\\train.csv")
# 預覽資料集
row_index = 0
row = train_df.iloc[row_index]
for col, val in row.items():
    if isinstance(val, str) and len(val) > 100:
        print(f"{col:25}: {val[:100]}...")   # truncate long text
    else:
        print(f"{col:25}: {val}")
# 數值與文字特徵
numeric_features = [c for c in train_df.select_dtypes(include=['number']).columns if c != 'metacritic_score']
print("All available numeric features :", numeric_features)
print("All available text features :", train_df.select_dtypes(include=['object']).columns.tolist())

"""# Load Data"""

# TODO(Boss baseline) - Feature Selection: 選擇適合的features進行訓練，可選features請參見csv檔欄位
# To check all available numeric features, uncomment the line below :
# print("All availbale numeric features :", train_df.select_dtypes(include=['number']).columns.tolist())
numeric_features = ['recommendations', 'positive', 'negative','price',
                    'average_playtime_forever','average_playtime_2weeks','median_playtime_forever','median_playtime_2weeks','peak_ccu','pct_pos_total','estimated_owners']

X_numeric = train_df[numeric_features].fillna(0).values
y = train_df['metacritic_score'].fillna(0).values.reshape(-1, 1)


# 預設只使用數值特徵
X = X_numeric

# TODO(Boss baseline) - Feature Selection: 使用文字欄位的Embedding捕捉特徵

# 如果想要使用embedding，可以取消以下程式碼註解
from sentence_transformers import SentenceTransformer
from sklearn.decomposition import PCA

# 要進行embedding的文字欄位
text_columns = ['reviews','detailed_description']

embedder = SentenceTransformer('all-mpnet-base-v2')

def extract_embeddings(df, col):
    print(f"Embedding column: {col}")
    texts = df[col].fillna("").astype(str).tolist()
    emb = embedder.encode(texts, batch_size=64, show_progress_bar=True, convert_to_numpy=True)
    return emb

def reduce_dim_with_pca(embeddings, n_components=64):
    pca = PCA(n_components=n_components)
    reduced = pca.fit_transform(embeddings)
    return reduced, pca

# 建立embeddings並用PCA降維
embeddings_reduced = []
pca_models = {}
for col in text_columns:
    emb = extract_embeddings(train_df, col)
    emb_reduced, pca_model = reduce_dim_with_pca(emb, n_components=100)
    embeddings_reduced.append(emb_reduced)
    pca_models[col] = pca_model

X_text_reduced = np.concatenate(embeddings_reduced, axis=1)

# 將數值特徵與文字特徵結合
X = np.concatenate([X_numeric, X_text_reduced], axis=1)


# ===== 對資料進行標準化 =====
"""原因:原始資料範圍->
recommendations: 0 - 100,000    ← 超大
positive:        0 - 500,000    ← 超超大
negative:        0 - 50,000
price:           0 - 60          ← 很小

梯度大小：
∂L/∂w_recommendations ≈ 50000  ← 巨大！
∂L/∂w_price ≈ 0.5              ← 很小

結果：
模型會偏向大數值的特徵，學習不穩定"""
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
target_scaler = StandardScaler()
y_scaled = target_scaler.fit_transform(y)

# ===== 切分 train/valid set: 可以自行調整訓練集與驗證集的比例 =====
"""用途：

Training Set (75%)：用來訓練模型（更新權重）
Validation Set (25%)：用來評估模型（不更新權重）"""
X_train, X_dev, y_train, y_dev = train_test_split(X_scaled, y_scaled, test_size=0.25, random_state=42)

"""# Dataset Class

"""

# ===== 資料集 =====
"""用途：
把 NumPy array 轉成 PyTorch 可以用的 Dataset 格式。"""
class SteamDataset(Dataset):
    def __init__(self, features, targets):
        self.features = torch.tensor(features, dtype=torch.float32)
        self.targets = torch.tensor(targets, dtype=torch.float32)
    def __len__(self):
        return len(self.features)
    def __getitem__(self, idx):
        return self.features[idx], self.targets[idx]

"""# Model Class"""

# TODO(Strong baseline) - 模型架構: 自行調整模型架構以提高模型能力
"""y_pred = W·x + b

具體來說：
metacritic_score = w1×recommendations + w2×positive + 
                   w3×negative + w4×price + b
                   
**結構圖：**
Input (4 features) → Linear Layer → Output (1 score)
[rec, pos, neg, price] → [W, b] → [score]"""
class LinearModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.fc = nn.Linear(input_dim, 1) #丟入4個features最後產出一個score

    def forward(self, x):
        return self.fc(x)


"""# Layer 1: Linear(4, 128)
輸入 4 個特徵 → 擴展到 128 維
為什麼？讓模型有更多「思考空間」來學習複雜模式

# ReLU (Rectified Linear Unit)
ReLU(x) = max(0, x)
作用：引入非線性，讓模型可以學習「如果-那麼」的邏輯

例如：
如果 positive > 10000 且 negative < 1000:
    高分
否則：
    低分

線性模型學不到這種邏輯，需要 ReLU

# Dropout(0.3)
隨機關掉 30% 的神經元
為什麼？防止過擬合
原理：強迫模型不依賴特定神經元，更加健壯

# Layer 2: Linear(128, 64)
128 維 → 壓縮到 64 維
逐漸收斂到答案

# Output: Linear(64, 1)
64 維 → 1 個數字（Metacritic Score）
```

**結構圖：**
```
Input (4) → Linear(4→128) → ReLU → Dropout
          → Linear(128→64) → ReLU → Dropout
          → Linear(64→1) → Output
```

**Linear vs MLP 的差異：**
```
Linear Model:
✅ 簡單快速
✅ 不容易過擬合
❌ 只能學線性關係
❌ 對複雜模式效果差

MLP Model:
✅ 可學習複雜非線性關係
✅ 表達能力強
❌ 容易過擬合
❌ 訓練較慢

*****加入Embedding(將文字轉換為多維向量進行分析->更準確)
Input Layer: 6 個數值特徵 + 768 個文字特徵 = 774 維
  ↓
Hidden Layer 1: 128 neurons
  ↓
Hidden Layer 2: 64 neurons
  ↓
Output: 1 個預測值

特徵維度: 774  ← 增加了 128 倍！
學習重點: 
- 數值關係（推薦數、價格）
- 語意關係（評論情感、遊戲特色）
- 數值+語意的交互作用

**但是原始 Embedding: 768 維
reviews_emb = embedder.encode(df['reviews'])  # (n_samples, 768)

# 太多維度會導致：
1. 訓練變慢
2. 容易過擬合
3. 計算資源需求大

# 用 PCA 降到 64-100 維
from sklearn.decomposition import PCA
pca = PCA(n_components=64)
reviews_reduced = pca.fit_transform(reviews_emb)  # (n_samples, 64)

# 保留了 80-90% 的資訊，但維度降低了 10 倍

"""
class MLPModel(nn.Module):

    def __init__(self, input_dim, hidden_dims=(128, 64), dropout=0.3):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dims[0]), # 第一層：input_dim -> 128，後接ReLU，好處是能夠引入非線性，讓模型學習更複雜的模式
            nn.ReLU(),
            nn.Dropout(dropout), # 設置Dropout能夠防止overfitting
            nn.Linear(hidden_dims[0], hidden_dims[1]), # 中間層：128 -> 64，接ReLU
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dims[1], 1), # 輸出層：64 -> 1
        )

    def forward(self, x):
        return self.net(x)

"""# Hyperparameter

1 epoch = 過完整個訓練集一次

例如：
訓練集 4000 筆
batch_size = 128
每個 epoch = 4000/128 = 32 個 batch

1000 epochs = 32,000 次權重更新


"""

# TODO(Medium baseline) - Training Hyperparameters: 自行調整訓練超參數來改善模型表現
n_epochs = 2500          # 訓練回合數
learning_rate = 1e-5     # 學習率
batch_size = 256      # 每次訓練取多少樣本
"""沒有正則化：
Loss = MSE(y_pred, y_true)

有正則化：
Loss = MSE + weight_decay × Σ(weights²) -> weight_decay可以調整太大的權重ex. weight_decay = 0.01
         ↑                    ↑
      原始損失          懲罰大權重

沒有正則化：

    模型可能學到：
    w1 = 1000, w2 = -500, w3 = 800
    → 對資料過度敏感，容易過擬合(overfitting)

    有正則化 (weight_decay=0.01)：
    強迫權重變小：
    w1 = 10, w2 = -5, w3 = 8
    → 更穩健，泛化能力好
"""
weight_decay = 0         # L2 regularization強度，緩解overfitting。Useful Reference:https://medium.com/analytics-vidhya/deep-learning-basics-weight-decay-3c68eb4344e9
shuffle_data = True      # 是否在每個 epoch 打亂資料訓練

"""# Train"""

# ===== 用DataLoader讀取資料集 =====
train_set = SteamDataset(X_train, y_train)
dev_set = SteamDataset(X_dev, y_dev)
train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=shuffle_data)
dev_loader = DataLoader(dev_set, batch_size=batch_size, shuffle=False)

# ===== Model / Optimizer / Loss =====
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = MLPModel(input_dim=X_train.shape[1]).to(device)  # TODO(Strong baseline) - 也可以換成 MLPModel
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
loss_fn = nn.MSELoss()
# ===== 訓練迴圈 =====
train_loss_history = []
val_rmse_history = []
train_rmse_history = []
for epoch in tqdm(range(n_epochs), desc="Training Progress"):
    model.train()
    total_loss = 0
    for x_batch, y_batch in train_loader:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)

        # 1. Forward Pass
        """
        # 具體做什麼：
        對於 Linear Model:
        preds = W·x + b 將x參數傳到linear model函數裡面

        對於 MLP:  將x參數傳到linear函數裡，並中途不斷穿插RELu以防這個x傳不到最後的神經元(因為防止梯度消失的問題)
        x → Linear → ReLU → Dropout → Linear → ReLU → Dropout → Linear → preds"""
        preds = model(x_batch)

        # 2. Compute Loss
        """loss = loss_fn(preds, y_batch) 調用Loss function計算loss

        # MSELoss 的公式：
        loss = (1/n) × Σ(pred - y_true)² 將傳入到函數裡的x->得出的preds進行loss計算

        例如：
        preds = [70, 65, 80]
        y_true = [75, 60, 82]
        loss = ((70-75)² + (65-60)² + (80-82)²) / 3
            = (25 + 25 + 4) / 3
            = 18.0"""
        loss = loss_fn(preds, y_batch)
    
        # 3. Backpropagation
        """optimizer.zero_grad()  # 清空舊梯度(要清空是因為pytorch梯度是累加的)

        # Batch 1
        optimizer.zero_grad()  → w.grad = 0
        loss.backward()        → w.grad = 3.0  ✓

        # Batch 2
        optimizer.zero_grad()  → w.grad = 0    ← 清空！
        loss.backward()        → w.grad = 2.0  ✓

        # Batch 3
        optimizer.zero_grad()  → w.grad = 0    ← 清空！
        loss.backward()        → w.grad = 1.5  ✓
        
        **每個 batch 都是乾淨的梯度，只代表當前這批資料的方向。
        不清空的話，新的計算會疊在舊的上面，答案就錯了
        
        loss.backward()         # 計算新梯度 

        #補充
        Forward Pass（前向）：原料流向成品，發現問題
        Backprop（反向）：從問題往回查，每個工序要負多少責任？

        # 做了什麼：
        計算 ∂Loss/∂w1, ∂Loss/∂w2, ..., ∂Loss/∂b
        告訴我們：「往哪個方向調整權重，Loss 會下降」"""
        optimizer.zero_grad()
        loss.backward()

        # 4. Optimize(根據Backpropagation->從 Loss 出發，往回計算每個權重對 Loss 的影響程度
        # 而後告訴 optimizer 每個權重該往哪個方向、調多少)
        """optimizer.step()

        # Adam optimizer 做了什麼：
        1. 計算一階動量（moving average of gradient）
        2. 計算二階動量（moving average of squared gradient）
        3. 用這些資訊更新權重

        簡化版：
        W_new = W_old - adaptive_lr × gradient
        其中 adaptive_lr 會根據歷史梯度自動調整"""
        optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    train_loss_history.append(avg_loss)
    # 驗證
    """訓練模式 (model.train()):
    Dropout 會隨機關掉神經元
    BatchNorm 會更新統計資訊

    評估模式 (model.eval()):
    Dropout 關閉（使用所有神經元）
    BatchNorm 使用固定的統計資訊"""
    # ========== 評估：計算 Train RMSE 和 Val RMSE ==========
    model.eval()
    
    # 1. 訓練集 RMSE
    train_preds_list, train_true_list = [], []
    with torch.no_grad():
        for x_batch, y_batch in train_loader:
            x_batch = x_batch.to(device)
            preds = model(x_batch)
            train_preds_list.append(preds.cpu().numpy())
            train_true_list.append(y_batch.cpu().numpy())
    
    train_pred_raw = np.vstack(train_preds_list)
    train_true_raw = np.vstack(train_true_list)
    train_pred_inv = target_scaler.inverse_transform(train_pred_raw)
    train_true_inv = target_scaler.inverse_transform(train_true_raw)
    train_rmse = np.sqrt(mean_squared_error(train_true_inv, train_pred_inv))
    train_rmse_history.append(train_rmse)
    
    # 2. 驗證集 RMSE
    preds_list, y_true_list = [], []
    with torch.no_grad():
        for x_batch, y_batch in dev_loader:
            x_batch = x_batch.to(device)
            y_batch = y_batch.to(device)
            preds = model(x_batch)
            preds_list.append(preds.cpu().numpy())
            y_true_list.append(y_batch.cpu().numpy())
    
    y_pred_raw = np.vstack(preds_list)
    y_true_raw = np.vstack(y_true_list)
    y_pred_inv = target_scaler.inverse_transform(y_pred_raw)
    y_true_inv = target_scaler.inverse_transform(y_true_raw)
    val_rmse = np.sqrt(mean_squared_error(y_true_inv, y_pred_inv))
    val_rmse_history.append(val_rmse)
    
    # 3. 計算 Gap
    gap = val_rmse - train_rmse
    
    # 4. 每 50 epochs 顯示詳細資訊
    if (epoch + 1) % 50 == 0:
        print(f"Epoch {epoch+1:4d}: Train Loss={avg_loss:.4f}, "
              f"Train RMSE={train_rmse:.4f}, Val RMSE={val_rmse:.4f}, "
              f"Gap={gap:.4f}")

# ===== Plot Curves =====
epochs = np.arange(1, n_epochs + 1)

plt.figure()
plt.plot(epochs, train_loss_history, label="Train Loss")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.title("Training Loss Curve")
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

plt.figure()
plt.plot(epochs, val_rmse_history, label="Validation RMSE")
plt.xlabel("Epoch")
plt.ylabel("RMSE (on original scale)")
plt.title("Validation RMSE Curve")
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

"""# Inference on Test Dataset"""

# ===== 載入測試集 =====
test_df = pd.read_csv("GENAI-ML-2025-HW5-Data\\test.csv")

# 處理測試集 numeric 特徵
X_test_num = test_df[numeric_features].fillna(0).values

# 處理文字embedding
reviews_embed = embedder.encode(test_df["reviews"].fillna("").astype(str).tolist(),
                               batch_size=64, show_progress_bar=True, convert_to_numpy=True)
short_desc_embed = embedder.encode(test_df["short_description"].fillna("").astype(str).tolist(),
                                   batch_size=64, show_progress_bar=True, convert_to_numpy=True)

# 用train時的PCA來降維
reviews_embed_reduced = pca_models['reviews'].transform(reviews_embed)
short_desc_embed_reduced = pca_models['short_description'].transform(short_desc_embed)

# 合併numeric+embedding
X_test_combined = np.hstack([X_test_num, reviews_embed_reduced, short_desc_embed_reduced])
# 用 train 的 scaler transform (跟 train 特徵維度一致)
X_test_scaled = scaler.transform(X_test_combined)
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32).to(device)

# ===== 模型推論 =====
model.eval()
with torch.no_grad():
    preds_scaled = model(X_test_tensor).cpu().numpy()
    preds = target_scaler.inverse_transform(preds_scaled).squeeze()

submission = pd.DataFrame({
    "appid": test_df["appid"],
    "metacritic_score": np.round(preds).astype(int)
})
submission.to_csv("submission.csv", index=False)
print("Output saved to submission.csv")